version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist s3://my-react-app-frontend-ghdwpaks --delete
      - aws cloudfront create-invalidation --distribution-id E2GKXOW93XW11B --paths "/*"
artifacts:
  files:
    - '**/*'
  base-directory: dist
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
